### ISSUE TITLE
Отсутствие scroll-zoom на карте *(

### ISSUE THREAD

**Issue by yackermann** [nazar-pc/CherryTea.org#2]
А можно включить скролл-зум? *)

``` js
_CherryTea_Default_uk.js:1265
map.behaviors.disable('scrollZoom');
```

**Comment by nazar-pc** [comment]
- на сайте старая версия системы, этот репозиторий содержит новую версию, которая, хм... [немного отличается](https://www.facebook.com/photo.php?fbid=825693764145911&set=a.141656292549665.24060.100001158846579&type=1&theater&notif_t=like_tagged), и будет выложена в течении суток
- отсутствие scroll-zoom было выключено сознательно, из-за этого были сложности с прокруткой страницы
- `_CherryTea_Default_uk.js:1265` - как видно из названия, минифицированный файл, который готовит система, так что не совсем понятно о какой строчке какого файла идет речь, но это и не важно уже)

**Comment by yackermann** [comment]
Понятененько.
P.S. Идея сервиса просто офигеть! :+1:
